#!/command/with-contenv bash
. "/usr/local/bin/logger"
program_name="janus"
# ==============================================================================
# janus
# Terminate janus
# ==============================================================================

echo "Stopping janus" | info "${program_name} "
killall -15 janus
