#!/command/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# janus
# Runs janus
# ==============================================================================

echo "Starting janus..." | info

# # Remove old socket if existing
# rm /zoneminder/run/janus.socket > /dev/null 2>&1

exec s6-setuidgid www-data \
    fdmove -c 2 1 \
      /usr/sbin/janus -d
